### ISSUE TITLE
Overlapping components near the searchbar

### ISSUE THREAD

**Issue by ansisme** [HridoyHazard/HazzWeather#100]
![image](https://github.com/HridoyHazard/HazzWeather/assets/91877814/83cf9b65-3c38-4f61-9911-17ab26f3a5a6)
The searchbar and the country suggestion texts are kinda overlapping. UI components not rendered properly.

**Comment by suvraghosh** [comment]
Hey @HridoyHazard  interested to work on this issue if possible can you assign it to me ?

**Comment by ansisme** [comment]
thanks @HridoyHazard, would work on it!
