### ISSUE TITLE
"The Only Weather App You Need !" not readable in dark mode

### ISSUE THREAD

**Issue by RoastedBrotato** [HridoyHazard/HazzWeather#106]
![issue2](https://github.com/HridoyHazard/HazzWeather/assets/43197835/6bfbc548-f0c0-4357-8601-b78e2582903f)

**Comment by LOGESH-B** [comment]
Hii @RoastedBrotato 
Can I get assigned?

**Comment by ashikjhonson** [comment]
Hey @RoastedBrotato, 
Could you please assign me this issue. 
Thank you.
