### ISSUE TITLE
bug: the dropdown isn't clickable, and doesn't take full width of the search bar making text hard to read. 

### ISSUE THREAD

**Issue by RoastedBrotato** [HridoyHazard/HazzWeather#112]

**Comment by rjangid9080** [comment]
hey @RoastedBrotato, Please provide an screenshot for this issue and with a related description which makes issue understandable

**Comment by Yash9276** [comment]
I would like to contribute to this issue under the Hacktoberfest tag
please assign this issue it to me
Thank You :)

**Comment by HridoyHazard** [comment]
plz go ahead and make a pr
