### ISSUE TITLE
Hey, add more language to Website

### ISSUE THREAD

**Issue by nileshlad09** [HridoyHazard/HazzWeather#28]
hey @HridoyHazard, I can add more languages to the website, so more people can use it
I like to add the Marathi Language
so please can you assign this issue to me

**Comment by nileshlad09** [comment]
Can you please add hacktoberfest label

**Comment by HridoyHazard** [comment]
first make a valid pr. after that i will add hacktoberfest label

**Comment by nileshlad09** [comment]
Ok
