### ISSUE TITLE
Error: Location not found

### ISSUE THREAD

**Issue by komalioruganti** [HridoyHazard/HazzWeather#39]
- No matter what location is entered it just shows "Location not found".
- It doesn't work even for the recommended locations(Dhaka, USA, Canada)

![image](https://user-images.githubusercontent.com/95839946/195507256-c054fd1c-de4e-4e8a-8129-c207e879ff95.png)

![image](https://user-images.githubusercontent.com/95839946/195507578-81ff7f86-fedf-4288-ab4b-760fd7810de7.png)

**Comment by HridoyHazard** [comment]
can you check now plz? i fixed the bug
