### ISSUE TITLE
Language change feature is not user-friendly.

### ISSUE THREAD

**Issue by DarkFalc0n** [HridoyHazard/HazzWeather#48]
The language drop-down should display the language names in the respective languages. 
For example, upon changing the language to chinese, all the other language names also get displayed in chinese. This can cause many troubles for people who only know one language. So, the chinese language name should be displayed in chinese, tamil in tamil letters and so on.
I would like to fix this issue.

**Comment by DarkFalc0n** [comment]
@HridoyHazard Which branch should fork and work on?

**Comment by HridoyHazard** [comment]
fork the main branch and create new branch and work that branch and make pr request

**Comment by DarkFalc0n** [comment]
@HridoyHazard Alright, you can check the PR.
