### ISSUE TITLE
fix same language showing two times 

### ISSUE THREAD

**Issue by HridoyHazard** [HridoyHazard/HazzWeather#64]
![bullsie](https://user-images.githubusercontent.com/71395891/195992058-95161317-4a8b-46f7-837c-1b3e57b9509d.jpg)
বাংলা and বাংলাদেশ both are same language.
বাংলা is language of বাংলাদেশ
can anybody fix it ?

**Comment by AyushmaanKaushik** [comment]
Hi, can I be assigned to this issue?

**Comment by HridoyHazard** [comment]
sure go on....
