### ISSUE TITLE
No Validations

### ISSUE THREAD

**Issue by vatsalsinghkv** [HridoyHazard/HazzWeather#76]
I am able to search for a location by just entering 'SPACES'. I'd like to add some form validations
<img width="1197" alt="Screenshot 2022-10-20 at 10 30 45 PM" src="https://user-images.githubusercontent.com/68834718/197012733-fc20e37f-7109-40ec-aa63-3c87475b4310.png">

**Comment by Rohan-webd** [comment]
Can i be assigned with this issue ?

**Comment by anshulkumarx7** [comment]
Can you please assign me ths??
