### ISSUE TITLE
[Add language] Want to add Hindi language in application

### ISSUE THREAD

**Issue by A-Spiral-Forge** [HridoyHazard/HazzWeather#82]
Add `hindi.json` in languages folder for Hindi language.

**Comment by A-Spiral-Forge** [comment]
please assign me this under hacktoberfest.

**Comment by HridoyHazard** [comment]
go ahead

**Comment by A-Spiral-Forge** [comment]
@HridoyHazard  you already accepted PR from other person this. 
Ref: #83
