### ISSUE TITLE
Broken link ! 

### ISSUE THREAD

**Issue by rohitroy-github** [HridoyHazard/HazzWeather#85]
The link to this is broken I guess. If it's relevant to the project, assign it to me, I'll put the link directly from Udemy ! 

![Screenshot (134)](https://user-images.githubusercontent.com/68563695/197375446-298a3e4e-01c3-4564-a38d-9d22c3f4513d.png)

**Comment by HridoyHazard** [comment]
wrong repository! check plz

**Comment by rohitroy-github** [comment]
You're right. Sorry for the inconvenience !
