### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by pratik12350** [HridoyHazard/HazzWeather#98]
Typo in README.md > setup guide

[README.md > Setup Guide](https://github.com/HridoyHazard/HazzWeather/blob/main/README.md#setup-guide)
It should be like this:
```diff
- - Click on your `avatar/uesrName` in navbar.
+ - Click on your `avatar/username` in navbar.
```

My first time contributing btw.

**Comment by pratik12350** [comment]
Im sorry but looks like theres something wrong, i cant add label or assign myself for this issue. Can someone assign me if possible?

**Comment by HridoyHazard** [comment]
go ahead and solve this and make a pr
